#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHamlLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EHamlDB")]
	public partial class EHamlDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAsaei_EHaml_Inquiry(Asaei_EHaml_Inquiry instance);
    partial void UpdateAsaei_EHaml_Inquiry(Asaei_EHaml_Inquiry instance);
    partial void DeleteAsaei_EHaml_Inquiry(Asaei_EHaml_Inquiry instance);
    partial void InsertAsaei_EHaml_ListeKalahayeKhatarnak(Asaei_EHaml_ListeKalahayeKhatarnak instance);
    partial void UpdateAsaei_EHaml_ListeKalahayeKhatarnak(Asaei_EHaml_ListeKalahayeKhatarnak instance);
    partial void DeleteAsaei_EHaml_ListeKalahayeKhatarnak(Asaei_EHaml_ListeKalahayeKhatarnak instance);
    partial void InsertAsaei_EHaml_NoeVasileyeHaml(Asaei_EHaml_NoeVasileyeHaml instance);
    partial void UpdateAsaei_EHaml_NoeVasileyeHaml(Asaei_EHaml_NoeVasileyeHaml instance);
    partial void DeleteAsaei_EHaml_NoeVasileyeHaml(Asaei_EHaml_NoeVasileyeHaml instance);
    partial void InsertAsaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz instance);
    partial void UpdateAsaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz instance);
    partial void DeleteAsaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz instance);
    partial void InsertAsaei_EHaml_ReplyToInquiry(Asaei_EHaml_ReplyToInquiry instance);
    partial void UpdateAsaei_EHaml_ReplyToInquiry(Asaei_EHaml_ReplyToInquiry instance);
    partial void DeleteAsaei_EHaml_ReplyToInquiry(Asaei_EHaml_ReplyToInquiry instance);
    partial void InsertAsaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz instance);
    partial void UpdateAsaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz instance);
    partial void DeleteAsaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz instance);
    #endregion
		
		public EHamlDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EHamlDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EHamlDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EHamlDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EHamlDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EHamlDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_Inquiry> Asaei_EHaml_Inquiries
		{
			get
			{
				return this.GetTable<Asaei_EHaml_Inquiry>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_ListeKalahayeKhatarnak> Asaei_EHaml_ListeKalahayeKhatarnaks
		{
			get
			{
				return this.GetTable<Asaei_EHaml_ListeKalahayeKhatarnak>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_NoeVasileyeHaml> Asaei_EHaml_NoeVasileyeHamls
		{
			get
			{
				return this.GetTable<Asaei_EHaml_NoeVasileyeHaml>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs
		{
			get
			{
				return this.GetTable<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_OstanVaShahr> Asaei_EHaml_OstanVaShahrs
		{
			get
			{
				return this.GetTable<Asaei_EHaml_OstanVaShahr>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_ReplyToInquiry> Asaei_EHaml_ReplyToInquiries
		{
			get
			{
				return this.GetTable<Asaei_EHaml_ReplyToInquiry>();
			}
		}
		
		public System.Data.Linq.Table<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs
		{
			get
			{
				return this.GetTable<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_Inquiry")]
	public partial class Asaei_EHaml_Inquiry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<int> _UserId;
		
		private string _HadafeShomaAzEstelam;
		
		private string _NoeVasileyeMoredeNiyaz;
		
		private string _NoeHaml;
		
		private string _NoeMahmoole;
		
		private string _NoeMahmoole2;
		
		private string _YekAksAzMahmoole;
		
		private string _CodeHsMahmoole;
		
		private string _VazneMahmooleKiloGeram;
		
		private string _ListeKalahayeKhatarnak;
		
		private string _NoeBasteBandi;
		
		private string _BaEhtesabeBimeyeMasooliyat;
		
		private string _FormeVooroodeArzeshBarAsaseVasileyeHaml;
		
		private string _FormeVorodeArzeshBarAsaseListeAdlBandi;
		
		private string _FormePakingList;
		
		private string _BaEhtesabeHazineyeBarGiriDarMabda;
		
		private string _EstelamBarAsase;
		
		private string _OstaneMabda;
		
		private string _MantageyeMabda;
		
		private string _ShahreMabda;
		
		private string _MogeiyateTahvilDadaneMahmooleBePeymankareHaml;
		
		private string _OstaneMagsad;
		
		private string _MantageyeMagsad;
		
		private string _ShahreMagsad;
		
		private string _BaEhtesabeHazineyeTakhliyeDarMagsad;
		
		private string _TarikheAgazeAmaliyatShamsi;
		
		private string _TarikheEtebareEstelamShamsi;
		
		private System.Nullable<System.DateTime> _TarikheAgazeAmaliyatMiladi;
		
		private System.Nullable<System.DateTime> _TarikheEtebareEstelamMiladi;
		
		private string _InquiryType;
		
		private string _CreateDateShamsi;
		
		private System.Nullable<System.DateTime> _CreateDateMiladi;
		
		private string _Tedad;
		
		private string _HadeAxareVazneMahmoole;
		
		private string _NoeVasileyeMoredeNiyaz2;
		
		private string _VazneHarVahedeMahmooleKiloGeram;
		
		private string _BaEhtesabeHazineyeOdateKantinereKhali;
		
		private EntitySet<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz> _Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs;
		
		private EntitySet<Asaei_EHaml_ReplyToInquiry> _Asaei_EHaml_ReplyToInquiries;
		
		private EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz> _Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnHadafeShomaAzEstelamChanging(string value);
    partial void OnHadafeShomaAzEstelamChanged();
    partial void OnNoeVasileyeMoredeNiyazChanging(string value);
    partial void OnNoeVasileyeMoredeNiyazChanged();
    partial void OnNoeHamlChanging(string value);
    partial void OnNoeHamlChanged();
    partial void OnNoeMahmooleChanging(string value);
    partial void OnNoeMahmooleChanged();
    partial void OnNoeMahmoole2Changing(string value);
    partial void OnNoeMahmoole2Changed();
    partial void OnYekAksAzMahmooleChanging(string value);
    partial void OnYekAksAzMahmooleChanged();
    partial void OnCodeHsMahmooleChanging(string value);
    partial void OnCodeHsMahmooleChanged();
    partial void OnVazneMahmooleKiloGeramChanging(string value);
    partial void OnVazneMahmooleKiloGeramChanged();
    partial void OnListeKalahayeKhatarnakChanging(string value);
    partial void OnListeKalahayeKhatarnakChanged();
    partial void OnNoeBasteBandiChanging(string value);
    partial void OnNoeBasteBandiChanged();
    partial void OnBaEhtesabeBimeyeMasooliyatChanging(string value);
    partial void OnBaEhtesabeBimeyeMasooliyatChanged();
    partial void OnFormeVooroodeArzeshBarAsaseVasileyeHamlChanging(string value);
    partial void OnFormeVooroodeArzeshBarAsaseVasileyeHamlChanged();
    partial void OnFormeVorodeArzeshBarAsaseListeAdlBandiChanging(string value);
    partial void OnFormeVorodeArzeshBarAsaseListeAdlBandiChanged();
    partial void OnFormePakingListChanging(string value);
    partial void OnFormePakingListChanged();
    partial void OnBaEhtesabeHazineyeBarGiriDarMabdaChanging(string value);
    partial void OnBaEhtesabeHazineyeBarGiriDarMabdaChanged();
    partial void OnEstelamBarAsaseChanging(string value);
    partial void OnEstelamBarAsaseChanged();
    partial void OnOstaneMabdaChanging(string value);
    partial void OnOstaneMabdaChanged();
    partial void OnMantageyeMabdaChanging(string value);
    partial void OnMantageyeMabdaChanged();
    partial void OnShahreMabdaChanging(string value);
    partial void OnShahreMabdaChanged();
    partial void OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanging(string value);
    partial void OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanged();
    partial void OnOstaneMagsadChanging(string value);
    partial void OnOstaneMagsadChanged();
    partial void OnMantageyeMagsadChanging(string value);
    partial void OnMantageyeMagsadChanged();
    partial void OnShahreMagsadChanging(string value);
    partial void OnShahreMagsadChanged();
    partial void OnBaEhtesabeHazineyeTakhliyeDarMagsadChanging(string value);
    partial void OnBaEhtesabeHazineyeTakhliyeDarMagsadChanged();
    partial void OnTarikheAgazeAmaliyatShamsiChanging(string value);
    partial void OnTarikheAgazeAmaliyatShamsiChanged();
    partial void OnTarikheEtebareEstelamShamsiChanging(string value);
    partial void OnTarikheEtebareEstelamShamsiChanged();
    partial void OnTarikheAgazeAmaliyatMiladiChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikheAgazeAmaliyatMiladiChanged();
    partial void OnTarikheEtebareEstelamMiladiChanging(System.Nullable<System.DateTime> value);
    partial void OnTarikheEtebareEstelamMiladiChanged();
    partial void OnInquiryTypeChanging(string value);
    partial void OnInquiryTypeChanged();
    partial void OnCreateDateShamsiChanging(string value);
    partial void OnCreateDateShamsiChanged();
    partial void OnCreateDateMiladiChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateMiladiChanged();
    partial void OnTedadChanging(string value);
    partial void OnTedadChanged();
    partial void OnHadeAxareVazneMahmooleChanging(string value);
    partial void OnHadeAxareVazneMahmooleChanged();
    partial void OnNoeVasileyeMoredeNiyaz2Changing(string value);
    partial void OnNoeVasileyeMoredeNiyaz2Changed();
    partial void OnVazneHarVahedeMahmooleKiloGeramChanging(string value);
    partial void OnVazneHarVahedeMahmooleKiloGeramChanged();
    partial void OnBaEhtesabeHazineyeOdateKantinereKhaliChanging(string value);
    partial void OnBaEhtesabeHazineyeOdateKantinereKhaliChanged();
    #endregion
		
		public Asaei_EHaml_Inquiry()
		{
			this._Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs = new EntitySet<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz>(new Action<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz>(this.attach_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs), new Action<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz>(this.detach_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs));
			this._Asaei_EHaml_ReplyToInquiries = new EntitySet<Asaei_EHaml_ReplyToInquiry>(new Action<Asaei_EHaml_ReplyToInquiry>(this.attach_Asaei_EHaml_ReplyToInquiries), new Action<Asaei_EHaml_ReplyToInquiry>(this.detach_Asaei_EHaml_ReplyToInquiries));
			this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs = new EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(new Action<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(this.attach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs), new Action<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(this.detach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HadafeShomaAzEstelam", DbType="NVarChar(1000)")]
		public string HadafeShomaAzEstelam
		{
			get
			{
				return this._HadafeShomaAzEstelam;
			}
			set
			{
				if ((this._HadafeShomaAzEstelam != value))
				{
					this.OnHadafeShomaAzEstelamChanging(value);
					this.SendPropertyChanging();
					this._HadafeShomaAzEstelam = value;
					this.SendPropertyChanged("HadafeShomaAzEstelam");
					this.OnHadafeShomaAzEstelamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeVasileyeMoredeNiyaz", DbType="NVarChar(1000)")]
		public string NoeVasileyeMoredeNiyaz
		{
			get
			{
				return this._NoeVasileyeMoredeNiyaz;
			}
			set
			{
				if ((this._NoeVasileyeMoredeNiyaz != value))
				{
					this.OnNoeVasileyeMoredeNiyazChanging(value);
					this.SendPropertyChanging();
					this._NoeVasileyeMoredeNiyaz = value;
					this.SendPropertyChanged("NoeVasileyeMoredeNiyaz");
					this.OnNoeVasileyeMoredeNiyazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeHaml", DbType="NVarChar(1000)")]
		public string NoeHaml
		{
			get
			{
				return this._NoeHaml;
			}
			set
			{
				if ((this._NoeHaml != value))
				{
					this.OnNoeHamlChanging(value);
					this.SendPropertyChanging();
					this._NoeHaml = value;
					this.SendPropertyChanged("NoeHaml");
					this.OnNoeHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeMahmoole", DbType="NVarChar(1000)")]
		public string NoeMahmoole
		{
			get
			{
				return this._NoeMahmoole;
			}
			set
			{
				if ((this._NoeMahmoole != value))
				{
					this.OnNoeMahmooleChanging(value);
					this.SendPropertyChanging();
					this._NoeMahmoole = value;
					this.SendPropertyChanged("NoeMahmoole");
					this.OnNoeMahmooleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeMahmoole2", DbType="NVarChar(1000)")]
		public string NoeMahmoole2
		{
			get
			{
				return this._NoeMahmoole2;
			}
			set
			{
				if ((this._NoeMahmoole2 != value))
				{
					this.OnNoeMahmoole2Changing(value);
					this.SendPropertyChanging();
					this._NoeMahmoole2 = value;
					this.SendPropertyChanged("NoeMahmoole2");
					this.OnNoeMahmoole2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YekAksAzMahmoole", DbType="NVarChar(1000)")]
		public string YekAksAzMahmoole
		{
			get
			{
				return this._YekAksAzMahmoole;
			}
			set
			{
				if ((this._YekAksAzMahmoole != value))
				{
					this.OnYekAksAzMahmooleChanging(value);
					this.SendPropertyChanging();
					this._YekAksAzMahmoole = value;
					this.SendPropertyChanged("YekAksAzMahmoole");
					this.OnYekAksAzMahmooleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeHsMahmoole", DbType="NVarChar(1000)")]
		public string CodeHsMahmoole
		{
			get
			{
				return this._CodeHsMahmoole;
			}
			set
			{
				if ((this._CodeHsMahmoole != value))
				{
					this.OnCodeHsMahmooleChanging(value);
					this.SendPropertyChanging();
					this._CodeHsMahmoole = value;
					this.SendPropertyChanged("CodeHsMahmoole");
					this.OnCodeHsMahmooleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VazneMahmooleKiloGeram", DbType="NVarChar(1000)")]
		public string VazneMahmooleKiloGeram
		{
			get
			{
				return this._VazneMahmooleKiloGeram;
			}
			set
			{
				if ((this._VazneMahmooleKiloGeram != value))
				{
					this.OnVazneMahmooleKiloGeramChanging(value);
					this.SendPropertyChanging();
					this._VazneMahmooleKiloGeram = value;
					this.SendPropertyChanged("VazneMahmooleKiloGeram");
					this.OnVazneMahmooleKiloGeramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListeKalahayeKhatarnak", DbType="NVarChar(1000)")]
		public string ListeKalahayeKhatarnak
		{
			get
			{
				return this._ListeKalahayeKhatarnak;
			}
			set
			{
				if ((this._ListeKalahayeKhatarnak != value))
				{
					this.OnListeKalahayeKhatarnakChanging(value);
					this.SendPropertyChanging();
					this._ListeKalahayeKhatarnak = value;
					this.SendPropertyChanged("ListeKalahayeKhatarnak");
					this.OnListeKalahayeKhatarnakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeBasteBandi", DbType="NVarChar(1000)")]
		public string NoeBasteBandi
		{
			get
			{
				return this._NoeBasteBandi;
			}
			set
			{
				if ((this._NoeBasteBandi != value))
				{
					this.OnNoeBasteBandiChanging(value);
					this.SendPropertyChanging();
					this._NoeBasteBandi = value;
					this.SendPropertyChanged("NoeBasteBandi");
					this.OnNoeBasteBandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaEhtesabeBimeyeMasooliyat", DbType="NVarChar(1000)")]
		public string BaEhtesabeBimeyeMasooliyat
		{
			get
			{
				return this._BaEhtesabeBimeyeMasooliyat;
			}
			set
			{
				if ((this._BaEhtesabeBimeyeMasooliyat != value))
				{
					this.OnBaEhtesabeBimeyeMasooliyatChanging(value);
					this.SendPropertyChanging();
					this._BaEhtesabeBimeyeMasooliyat = value;
					this.SendPropertyChanged("BaEhtesabeBimeyeMasooliyat");
					this.OnBaEhtesabeBimeyeMasooliyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormeVooroodeArzeshBarAsaseVasileyeHaml", DbType="NVarChar(1000)")]
		public string FormeVooroodeArzeshBarAsaseVasileyeHaml
		{
			get
			{
				return this._FormeVooroodeArzeshBarAsaseVasileyeHaml;
			}
			set
			{
				if ((this._FormeVooroodeArzeshBarAsaseVasileyeHaml != value))
				{
					this.OnFormeVooroodeArzeshBarAsaseVasileyeHamlChanging(value);
					this.SendPropertyChanging();
					this._FormeVooroodeArzeshBarAsaseVasileyeHaml = value;
					this.SendPropertyChanged("FormeVooroodeArzeshBarAsaseVasileyeHaml");
					this.OnFormeVooroodeArzeshBarAsaseVasileyeHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormeVorodeArzeshBarAsaseListeAdlBandi", DbType="NVarChar(1000)")]
		public string FormeVorodeArzeshBarAsaseListeAdlBandi
		{
			get
			{
				return this._FormeVorodeArzeshBarAsaseListeAdlBandi;
			}
			set
			{
				if ((this._FormeVorodeArzeshBarAsaseListeAdlBandi != value))
				{
					this.OnFormeVorodeArzeshBarAsaseListeAdlBandiChanging(value);
					this.SendPropertyChanging();
					this._FormeVorodeArzeshBarAsaseListeAdlBandi = value;
					this.SendPropertyChanged("FormeVorodeArzeshBarAsaseListeAdlBandi");
					this.OnFormeVorodeArzeshBarAsaseListeAdlBandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormePakingList", DbType="NVarChar(1000)")]
		public string FormePakingList
		{
			get
			{
				return this._FormePakingList;
			}
			set
			{
				if ((this._FormePakingList != value))
				{
					this.OnFormePakingListChanging(value);
					this.SendPropertyChanging();
					this._FormePakingList = value;
					this.SendPropertyChanged("FormePakingList");
					this.OnFormePakingListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaEhtesabeHazineyeBarGiriDarMabda", DbType="NVarChar(1000)")]
		public string BaEhtesabeHazineyeBarGiriDarMabda
		{
			get
			{
				return this._BaEhtesabeHazineyeBarGiriDarMabda;
			}
			set
			{
				if ((this._BaEhtesabeHazineyeBarGiriDarMabda != value))
				{
					this.OnBaEhtesabeHazineyeBarGiriDarMabdaChanging(value);
					this.SendPropertyChanging();
					this._BaEhtesabeHazineyeBarGiriDarMabda = value;
					this.SendPropertyChanged("BaEhtesabeHazineyeBarGiriDarMabda");
					this.OnBaEhtesabeHazineyeBarGiriDarMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstelamBarAsase", DbType="NVarChar(1000)")]
		public string EstelamBarAsase
		{
			get
			{
				return this._EstelamBarAsase;
			}
			set
			{
				if ((this._EstelamBarAsase != value))
				{
					this.OnEstelamBarAsaseChanging(value);
					this.SendPropertyChanging();
					this._EstelamBarAsase = value;
					this.SendPropertyChanged("EstelamBarAsase");
					this.OnEstelamBarAsaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OstaneMabda", DbType="NVarChar(1000)")]
		public string OstaneMabda
		{
			get
			{
				return this._OstaneMabda;
			}
			set
			{
				if ((this._OstaneMabda != value))
				{
					this.OnOstaneMabdaChanging(value);
					this.SendPropertyChanging();
					this._OstaneMabda = value;
					this.SendPropertyChanged("OstaneMabda");
					this.OnOstaneMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MantageyeMabda", DbType="NVarChar(1000)")]
		public string MantageyeMabda
		{
			get
			{
				return this._MantageyeMabda;
			}
			set
			{
				if ((this._MantageyeMabda != value))
				{
					this.OnMantageyeMabdaChanging(value);
					this.SendPropertyChanging();
					this._MantageyeMabda = value;
					this.SendPropertyChanged("MantageyeMabda");
					this.OnMantageyeMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShahreMabda", DbType="NVarChar(1000)")]
		public string ShahreMabda
		{
			get
			{
				return this._ShahreMabda;
			}
			set
			{
				if ((this._ShahreMabda != value))
				{
					this.OnShahreMabdaChanging(value);
					this.SendPropertyChanging();
					this._ShahreMabda = value;
					this.SendPropertyChanged("ShahreMabda");
					this.OnShahreMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MogeiyateTahvilDadaneMahmooleBePeymankareHaml", DbType="NVarChar(1000)")]
		public string MogeiyateTahvilDadaneMahmooleBePeymankareHaml
		{
			get
			{
				return this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml;
			}
			set
			{
				if ((this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml != value))
				{
					this.OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanging(value);
					this.SendPropertyChanging();
					this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml = value;
					this.SendPropertyChanged("MogeiyateTahvilDadaneMahmooleBePeymankareHaml");
					this.OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OstaneMagsad", DbType="NVarChar(1000)")]
		public string OstaneMagsad
		{
			get
			{
				return this._OstaneMagsad;
			}
			set
			{
				if ((this._OstaneMagsad != value))
				{
					this.OnOstaneMagsadChanging(value);
					this.SendPropertyChanging();
					this._OstaneMagsad = value;
					this.SendPropertyChanged("OstaneMagsad");
					this.OnOstaneMagsadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MantageyeMagsad", DbType="NVarChar(1000)")]
		public string MantageyeMagsad
		{
			get
			{
				return this._MantageyeMagsad;
			}
			set
			{
				if ((this._MantageyeMagsad != value))
				{
					this.OnMantageyeMagsadChanging(value);
					this.SendPropertyChanging();
					this._MantageyeMagsad = value;
					this.SendPropertyChanged("MantageyeMagsad");
					this.OnMantageyeMagsadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShahreMagsad", DbType="NVarChar(1000)")]
		public string ShahreMagsad
		{
			get
			{
				return this._ShahreMagsad;
			}
			set
			{
				if ((this._ShahreMagsad != value))
				{
					this.OnShahreMagsadChanging(value);
					this.SendPropertyChanging();
					this._ShahreMagsad = value;
					this.SendPropertyChanged("ShahreMagsad");
					this.OnShahreMagsadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaEhtesabeHazineyeTakhliyeDarMagsad", DbType="NVarChar(1000)")]
		public string BaEhtesabeHazineyeTakhliyeDarMagsad
		{
			get
			{
				return this._BaEhtesabeHazineyeTakhliyeDarMagsad;
			}
			set
			{
				if ((this._BaEhtesabeHazineyeTakhliyeDarMagsad != value))
				{
					this.OnBaEhtesabeHazineyeTakhliyeDarMagsadChanging(value);
					this.SendPropertyChanging();
					this._BaEhtesabeHazineyeTakhliyeDarMagsad = value;
					this.SendPropertyChanged("BaEhtesabeHazineyeTakhliyeDarMagsad");
					this.OnBaEhtesabeHazineyeTakhliyeDarMagsadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikheAgazeAmaliyatShamsi", DbType="NVarChar(1000)")]
		public string TarikheAgazeAmaliyatShamsi
		{
			get
			{
				return this._TarikheAgazeAmaliyatShamsi;
			}
			set
			{
				if ((this._TarikheAgazeAmaliyatShamsi != value))
				{
					this.OnTarikheAgazeAmaliyatShamsiChanging(value);
					this.SendPropertyChanging();
					this._TarikheAgazeAmaliyatShamsi = value;
					this.SendPropertyChanged("TarikheAgazeAmaliyatShamsi");
					this.OnTarikheAgazeAmaliyatShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikheEtebareEstelamShamsi", DbType="NVarChar(1000)")]
		public string TarikheEtebareEstelamShamsi
		{
			get
			{
				return this._TarikheEtebareEstelamShamsi;
			}
			set
			{
				if ((this._TarikheEtebareEstelamShamsi != value))
				{
					this.OnTarikheEtebareEstelamShamsiChanging(value);
					this.SendPropertyChanging();
					this._TarikheEtebareEstelamShamsi = value;
					this.SendPropertyChanged("TarikheEtebareEstelamShamsi");
					this.OnTarikheEtebareEstelamShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikheAgazeAmaliyatMiladi", DbType="Date")]
		public System.Nullable<System.DateTime> TarikheAgazeAmaliyatMiladi
		{
			get
			{
				return this._TarikheAgazeAmaliyatMiladi;
			}
			set
			{
				if ((this._TarikheAgazeAmaliyatMiladi != value))
				{
					this.OnTarikheAgazeAmaliyatMiladiChanging(value);
					this.SendPropertyChanging();
					this._TarikheAgazeAmaliyatMiladi = value;
					this.SendPropertyChanged("TarikheAgazeAmaliyatMiladi");
					this.OnTarikheAgazeAmaliyatMiladiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikheEtebareEstelamMiladi", DbType="Date")]
		public System.Nullable<System.DateTime> TarikheEtebareEstelamMiladi
		{
			get
			{
				return this._TarikheEtebareEstelamMiladi;
			}
			set
			{
				if ((this._TarikheEtebareEstelamMiladi != value))
				{
					this.OnTarikheEtebareEstelamMiladiChanging(value);
					this.SendPropertyChanging();
					this._TarikheEtebareEstelamMiladi = value;
					this.SendPropertyChanged("TarikheEtebareEstelamMiladi");
					this.OnTarikheEtebareEstelamMiladiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryType", DbType="NVarChar(1000)")]
		public string InquiryType
		{
			get
			{
				return this._InquiryType;
			}
			set
			{
				if ((this._InquiryType != value))
				{
					this.OnInquiryTypeChanging(value);
					this.SendPropertyChanging();
					this._InquiryType = value;
					this.SendPropertyChanged("InquiryType");
					this.OnInquiryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateShamsi", DbType="NVarChar(1000)")]
		public string CreateDateShamsi
		{
			get
			{
				return this._CreateDateShamsi;
			}
			set
			{
				if ((this._CreateDateShamsi != value))
				{
					this.OnCreateDateShamsiChanging(value);
					this.SendPropertyChanging();
					this._CreateDateShamsi = value;
					this.SendPropertyChanged("CreateDateShamsi");
					this.OnCreateDateShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateMiladi", DbType="Date")]
		public System.Nullable<System.DateTime> CreateDateMiladi
		{
			get
			{
				return this._CreateDateMiladi;
			}
			set
			{
				if ((this._CreateDateMiladi != value))
				{
					this.OnCreateDateMiladiChanging(value);
					this.SendPropertyChanging();
					this._CreateDateMiladi = value;
					this.SendPropertyChanged("CreateDateMiladi");
					this.OnCreateDateMiladiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad", DbType="NVarChar(1000)")]
		public string Tedad
		{
			get
			{
				return this._Tedad;
			}
			set
			{
				if ((this._Tedad != value))
				{
					this.OnTedadChanging(value);
					this.SendPropertyChanging();
					this._Tedad = value;
					this.SendPropertyChanged("Tedad");
					this.OnTedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HadeAxareVazneMahmoole", DbType="NVarChar(1000)")]
		public string HadeAxareVazneMahmoole
		{
			get
			{
				return this._HadeAxareVazneMahmoole;
			}
			set
			{
				if ((this._HadeAxareVazneMahmoole != value))
				{
					this.OnHadeAxareVazneMahmooleChanging(value);
					this.SendPropertyChanging();
					this._HadeAxareVazneMahmoole = value;
					this.SendPropertyChanged("HadeAxareVazneMahmoole");
					this.OnHadeAxareVazneMahmooleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoeVasileyeMoredeNiyaz2", DbType="NVarChar(1000)")]
		public string NoeVasileyeMoredeNiyaz2
		{
			get
			{
				return this._NoeVasileyeMoredeNiyaz2;
			}
			set
			{
				if ((this._NoeVasileyeMoredeNiyaz2 != value))
				{
					this.OnNoeVasileyeMoredeNiyaz2Changing(value);
					this.SendPropertyChanging();
					this._NoeVasileyeMoredeNiyaz2 = value;
					this.SendPropertyChanged("NoeVasileyeMoredeNiyaz2");
					this.OnNoeVasileyeMoredeNiyaz2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VazneHarVahedeMahmooleKiloGeram", DbType="NVarChar(1000)")]
		public string VazneHarVahedeMahmooleKiloGeram
		{
			get
			{
				return this._VazneHarVahedeMahmooleKiloGeram;
			}
			set
			{
				if ((this._VazneHarVahedeMahmooleKiloGeram != value))
				{
					this.OnVazneHarVahedeMahmooleKiloGeramChanging(value);
					this.SendPropertyChanging();
					this._VazneHarVahedeMahmooleKiloGeram = value;
					this.SendPropertyChanged("VazneHarVahedeMahmooleKiloGeram");
					this.OnVazneHarVahedeMahmooleKiloGeramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaEhtesabeHazineyeOdateKantinereKhali", DbType="NVarChar(1000)")]
		public string BaEhtesabeHazineyeOdateKantinereKhali
		{
			get
			{
				return this._BaEhtesabeHazineyeOdateKantinereKhali;
			}
			set
			{
				if ((this._BaEhtesabeHazineyeOdateKantinereKhali != value))
				{
					this.OnBaEhtesabeHazineyeOdateKantinereKhaliChanging(value);
					this.SendPropertyChanging();
					this._BaEhtesabeHazineyeOdateKantinereKhali = value;
					this.SendPropertyChanged("BaEhtesabeHazineyeOdateKantinereKhali");
					this.OnBaEhtesabeHazineyeOdateKantinereKhaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs", ThisKey="Id", OtherKey="InquiryID")]
		public EntitySet<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs
		{
			get
			{
				return this._Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs;
			}
			set
			{
				this._Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_ReplyToInquiry", Storage="_Asaei_EHaml_ReplyToInquiries", ThisKey="Id", OtherKey="InquiryId")]
		public EntitySet<Asaei_EHaml_ReplyToInquiry> Asaei_EHaml_ReplyToInquiries
		{
			get
			{
				return this._Asaei_EHaml_ReplyToInquiries;
			}
			set
			{
				this._Asaei_EHaml_ReplyToInquiries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs", ThisKey="Id", OtherKey="InquiryId")]
		public EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs
		{
			get
			{
				return this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs;
			}
			set
			{
				this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = this;
		}
		
		private void detach_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = null;
		}
		
		private void attach_Asaei_EHaml_ReplyToInquiries(Asaei_EHaml_ReplyToInquiry entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = this;
		}
		
		private void detach_Asaei_EHaml_ReplyToInquiries(Asaei_EHaml_ReplyToInquiry entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = null;
		}
		
		private void attach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = this;
		}
		
		private void detach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_Inquiry = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_ListeKalahayeKhatarnak")]
	public partial class Asaei_EHaml_ListeKalahayeKhatarnak : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<double> _ShomareyeTartib;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShomareyeTartibChanging(System.Nullable<double> value);
    partial void OnShomareyeTartibChanged();
    #endregion
		
		public Asaei_EHaml_ListeKalahayeKhatarnak()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareyeTartib", DbType="Float")]
		public System.Nullable<double> ShomareyeTartib
		{
			get
			{
				return this._ShomareyeTartib;
			}
			set
			{
				if ((this._ShomareyeTartib != value))
				{
					this.OnShomareyeTartibChanging(value);
					this.SendPropertyChanging();
					this._ShomareyeTartib = value;
					this.SendPropertyChanged("ShomareyeTartib");
					this.OnShomareyeTartibChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_NoeVasileyeHaml")]
	public partial class Asaei_EHaml_NoeVasileyeHaml : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NameVasile;
		
		private System.Nullable<int> _ShomareyeTartib;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameVasileChanging(string value);
    partial void OnNameVasileChanged();
    partial void OnShomareyeTartibChanging(System.Nullable<int> value);
    partial void OnShomareyeTartibChanged();
    #endregion
		
		public Asaei_EHaml_NoeVasileyeHaml()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameVasile", DbType="NVarChar(1000)")]
		public string NameVasile
		{
			get
			{
				return this._NameVasile;
			}
			set
			{
				if ((this._NameVasile != value))
				{
					this.OnNameVasileChanging(value);
					this.SendPropertyChanging();
					this._NameVasile = value;
					this.SendPropertyChanged("NameVasile");
					this.OnNameVasileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareyeTartib", DbType="Int")]
		public System.Nullable<int> ShomareyeTartib
		{
			get
			{
				return this._ShomareyeTartib;
			}
			set
			{
				if ((this._ShomareyeTartib != value))
				{
					this.OnShomareyeTartibChanging(value);
					this.SendPropertyChanging();
					this._ShomareyeTartib = value;
					this.SendPropertyChanged("ShomareyeTartib");
					this.OnShomareyeTartibChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz")]
	public partial class Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _InquiryID;
		
		private string _InquiryType;
		
		private string _VasileName;
		
		private System.Nullable<short> _Tedad;
		
		private EntityRef<Asaei_EHaml_Inquiry> _Asaei_EHaml_Inquiry;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnInquiryIDChanging(System.Nullable<long> value);
    partial void OnInquiryIDChanged();
    partial void OnInquiryTypeChanging(string value);
    partial void OnInquiryTypeChanged();
    partial void OnVasileNameChanging(string value);
    partial void OnVasileNameChanged();
    partial void OnTedadChanging(System.Nullable<short> value);
    partial void OnTedadChanged();
    #endregion
		
		public Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz()
		{
			this._Asaei_EHaml_Inquiry = default(EntityRef<Asaei_EHaml_Inquiry>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryID", DbType="BigInt")]
		public System.Nullable<long> InquiryID
		{
			get
			{
				return this._InquiryID;
			}
			set
			{
				if ((this._InquiryID != value))
				{
					if (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInquiryIDChanging(value);
					this.SendPropertyChanging();
					this._InquiryID = value;
					this.SendPropertyChanged("InquiryID");
					this.OnInquiryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryType", DbType="NVarChar(1000)")]
		public string InquiryType
		{
			get
			{
				return this._InquiryType;
			}
			set
			{
				if ((this._InquiryType != value))
				{
					this.OnInquiryTypeChanging(value);
					this.SendPropertyChanging();
					this._InquiryType = value;
					this.SendPropertyChanged("InquiryType");
					this.OnInquiryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VasileName", DbType="NVarChar(1000)")]
		public string VasileName
		{
			get
			{
				return this._VasileName;
			}
			set
			{
				if ((this._VasileName != value))
				{
					this.OnVasileNameChanging(value);
					this.SendPropertyChanging();
					this._VasileName = value;
					this.SendPropertyChanged("VasileName");
					this.OnVasileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad", DbType="SmallInt")]
		public System.Nullable<short> Tedad
		{
			get
			{
				return this._Tedad;
			}
			set
			{
				if ((this._Tedad != value))
				{
					this.OnTedadChanging(value);
					this.SendPropertyChanging();
					this._Tedad = value;
					this.SendPropertyChanged("Tedad");
					this.OnTedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_Inquiry", ThisKey="InquiryID", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Asaei_EHaml_Inquiry Asaei_EHaml_Inquiry
		{
			get
			{
				return this._Asaei_EHaml_Inquiry.Entity;
			}
			set
			{
				Asaei_EHaml_Inquiry previousValue = this._Asaei_EHaml_Inquiry.Entity;
				if (((previousValue != value) 
							|| (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asaei_EHaml_Inquiry.Entity = null;
						previousValue.Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs.Remove(this);
					}
					this._Asaei_EHaml_Inquiry.Entity = value;
					if ((value != null))
					{
						value.Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyazs.Add(this);
						this._InquiryID = value.Id;
					}
					else
					{
						this._InquiryID = default(Nullable<long>);
					}
					this.SendPropertyChanged("Asaei_EHaml_Inquiry");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_OstanVaShahr")]
	public partial class Asaei_EHaml_OstanVaShahr
	{
		
		private System.Nullable<double> _Id;
		
		private string _Shahrestan;
		
		private string _MarkazeShahrestan;
		
		private System.Nullable<double> _TarikheTasis;
		
		private System.Nullable<double> _CodeTagsimat;
		
		private string _Ostan;
		
		private string _GozaresheTojihi;
		
		public Asaei_EHaml_OstanVaShahr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Float")]
		public System.Nullable<double> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shahrestan", DbType="NVarChar(1000)")]
		public string Shahrestan
		{
			get
			{
				return this._Shahrestan;
			}
			set
			{
				if ((this._Shahrestan != value))
				{
					this._Shahrestan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkazeShahrestan", DbType="NVarChar(1000)")]
		public string MarkazeShahrestan
		{
			get
			{
				return this._MarkazeShahrestan;
			}
			set
			{
				if ((this._MarkazeShahrestan != value))
				{
					this._MarkazeShahrestan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikheTasis", DbType="Float")]
		public System.Nullable<double> TarikheTasis
		{
			get
			{
				return this._TarikheTasis;
			}
			set
			{
				if ((this._TarikheTasis != value))
				{
					this._TarikheTasis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeTagsimat", DbType="Float")]
		public System.Nullable<double> CodeTagsimat
		{
			get
			{
				return this._CodeTagsimat;
			}
			set
			{
				if ((this._CodeTagsimat != value))
				{
					this._CodeTagsimat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ostan", DbType="NVarChar(1000)")]
		public string Ostan
		{
			get
			{
				return this._Ostan;
			}
			set
			{
				if ((this._Ostan != value))
				{
					this._Ostan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GozaresheTojihi", DbType="NVarChar(1000)")]
		public string GozaresheTojihi
		{
			get
			{
				return this._GozaresheTojihi;
			}
			set
			{
				if ((this._GozaresheTojihi != value))
				{
					this._GozaresheTojihi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_ReplyToInquiry")]
	public partial class Asaei_EHaml_ReplyToInquiry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _InquiryId;
		
		private string _InquiryType;
		
		private int _ServentUserId;
		
		private string _KoleModatZamaneHaml;
		
		private string _ZamaneAmadegiBarayShoorooeAmaliyatShamsi;
		
		private System.Nullable<System.DateTime> _ZamaneAmadegiBarayShoorooAmaliyatMiladi;
		
		private string _GozaresheAmaliyateRoozane;
		
		private string _PishbiniEmkanPaziriyeAmaliyat;
		
		private string _GeymateKol;
		
		private string _GeymateVahed;
		
		private string _GeymateKolBarAsaseListeAdlBandi;
		
		private string _Vaziyat;
		
		private string _MogeiyateTahvilDadaneMahmooleBePeymankareHaml;
		
		private string _PasokhGooyiBarAsase;
		
		private string _PasokhGooyiBarAsaseVasileyeHaml;
		
		private string _GeymatBeEzayeHarTon;
		
		private string _FormePasokheGeymateHamleSangin;
		
		private string _BaEhtesabeHazineyeOdateCantinereKhali;
		
		private string _CreateDateShamsi;
		
		private System.Nullable<System.DateTime> _CreateDateMiladi;
		
		private EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz> _Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs;
		
		private EntityRef<Asaei_EHaml_Inquiry> _Asaei_EHaml_Inquiry;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnInquiryIdChanging(System.Nullable<long> value);
    partial void OnInquiryIdChanged();
    partial void OnInquiryTypeChanging(string value);
    partial void OnInquiryTypeChanged();
    partial void OnServentUserIdChanging(int value);
    partial void OnServentUserIdChanged();
    partial void OnKoleModatZamaneHamlChanging(string value);
    partial void OnKoleModatZamaneHamlChanged();
    partial void OnZamaneAmadegiBarayShoorooeAmaliyatShamsiChanging(string value);
    partial void OnZamaneAmadegiBarayShoorooeAmaliyatShamsiChanged();
    partial void OnZamaneAmadegiBarayShoorooAmaliyatMiladiChanging(System.Nullable<System.DateTime> value);
    partial void OnZamaneAmadegiBarayShoorooAmaliyatMiladiChanged();
    partial void OnGozaresheAmaliyateRoozaneChanging(string value);
    partial void OnGozaresheAmaliyateRoozaneChanged();
    partial void OnPishbiniEmkanPaziriyeAmaliyatChanging(string value);
    partial void OnPishbiniEmkanPaziriyeAmaliyatChanged();
    partial void OnGeymateKolChanging(string value);
    partial void OnGeymateKolChanged();
    partial void OnGeymateVahedChanging(string value);
    partial void OnGeymateVahedChanged();
    partial void OnGeymateKolBarAsaseListeAdlBandiChanging(string value);
    partial void OnGeymateKolBarAsaseListeAdlBandiChanged();
    partial void OnVaziyatChanging(string value);
    partial void OnVaziyatChanged();
    partial void OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanging(string value);
    partial void OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanged();
    partial void OnPasokhGooyiBarAsaseChanging(string value);
    partial void OnPasokhGooyiBarAsaseChanged();
    partial void OnPasokhGooyiBarAsaseVasileyeHamlChanging(string value);
    partial void OnPasokhGooyiBarAsaseVasileyeHamlChanged();
    partial void OnGeymatBeEzayeHarTonChanging(string value);
    partial void OnGeymatBeEzayeHarTonChanged();
    partial void OnFormePasokheGeymateHamleSanginChanging(string value);
    partial void OnFormePasokheGeymateHamleSanginChanged();
    partial void OnBaEhtesabeHazineyeOdateCantinereKhaliChanging(string value);
    partial void OnBaEhtesabeHazineyeOdateCantinereKhaliChanged();
    partial void OnCreateDateShamsiChanging(string value);
    partial void OnCreateDateShamsiChanged();
    partial void OnCreateDateMiladiChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateMiladiChanged();
    #endregion
		
		public Asaei_EHaml_ReplyToInquiry()
		{
			this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs = new EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(new Action<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(this.attach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs), new Action<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz>(this.detach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs));
			this._Asaei_EHaml_Inquiry = default(EntityRef<Asaei_EHaml_Inquiry>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryId", DbType="BigInt")]
		public System.Nullable<long> InquiryId
		{
			get
			{
				return this._InquiryId;
			}
			set
			{
				if ((this._InquiryId != value))
				{
					if (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInquiryIdChanging(value);
					this.SendPropertyChanging();
					this._InquiryId = value;
					this.SendPropertyChanged("InquiryId");
					this.OnInquiryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryType", DbType="NVarChar(1000)")]
		public string InquiryType
		{
			get
			{
				return this._InquiryType;
			}
			set
			{
				if ((this._InquiryType != value))
				{
					this.OnInquiryTypeChanging(value);
					this.SendPropertyChanging();
					this._InquiryType = value;
					this.SendPropertyChanged("InquiryType");
					this.OnInquiryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServentUserId", DbType="Int NOT NULL")]
		public int ServentUserId
		{
			get
			{
				return this._ServentUserId;
			}
			set
			{
				if ((this._ServentUserId != value))
				{
					this.OnServentUserIdChanging(value);
					this.SendPropertyChanging();
					this._ServentUserId = value;
					this.SendPropertyChanged("ServentUserId");
					this.OnServentUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoleModatZamaneHaml", DbType="NVarChar(1000)")]
		public string KoleModatZamaneHaml
		{
			get
			{
				return this._KoleModatZamaneHaml;
			}
			set
			{
				if ((this._KoleModatZamaneHaml != value))
				{
					this.OnKoleModatZamaneHamlChanging(value);
					this.SendPropertyChanging();
					this._KoleModatZamaneHaml = value;
					this.SendPropertyChanged("KoleModatZamaneHaml");
					this.OnKoleModatZamaneHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZamaneAmadegiBarayShoorooeAmaliyatShamsi", DbType="NVarChar(1000)")]
		public string ZamaneAmadegiBarayShoorooeAmaliyatShamsi
		{
			get
			{
				return this._ZamaneAmadegiBarayShoorooeAmaliyatShamsi;
			}
			set
			{
				if ((this._ZamaneAmadegiBarayShoorooeAmaliyatShamsi != value))
				{
					this.OnZamaneAmadegiBarayShoorooeAmaliyatShamsiChanging(value);
					this.SendPropertyChanging();
					this._ZamaneAmadegiBarayShoorooeAmaliyatShamsi = value;
					this.SendPropertyChanged("ZamaneAmadegiBarayShoorooeAmaliyatShamsi");
					this.OnZamaneAmadegiBarayShoorooeAmaliyatShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZamaneAmadegiBarayShoorooAmaliyatMiladi", DbType="Date")]
		public System.Nullable<System.DateTime> ZamaneAmadegiBarayShoorooAmaliyatMiladi
		{
			get
			{
				return this._ZamaneAmadegiBarayShoorooAmaliyatMiladi;
			}
			set
			{
				if ((this._ZamaneAmadegiBarayShoorooAmaliyatMiladi != value))
				{
					this.OnZamaneAmadegiBarayShoorooAmaliyatMiladiChanging(value);
					this.SendPropertyChanging();
					this._ZamaneAmadegiBarayShoorooAmaliyatMiladi = value;
					this.SendPropertyChanged("ZamaneAmadegiBarayShoorooAmaliyatMiladi");
					this.OnZamaneAmadegiBarayShoorooAmaliyatMiladiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GozaresheAmaliyateRoozane", DbType="NVarChar(1000)")]
		public string GozaresheAmaliyateRoozane
		{
			get
			{
				return this._GozaresheAmaliyateRoozane;
			}
			set
			{
				if ((this._GozaresheAmaliyateRoozane != value))
				{
					this.OnGozaresheAmaliyateRoozaneChanging(value);
					this.SendPropertyChanging();
					this._GozaresheAmaliyateRoozane = value;
					this.SendPropertyChanged("GozaresheAmaliyateRoozane");
					this.OnGozaresheAmaliyateRoozaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PishbiniEmkanPaziriyeAmaliyat", DbType="NVarChar(1000)")]
		public string PishbiniEmkanPaziriyeAmaliyat
		{
			get
			{
				return this._PishbiniEmkanPaziriyeAmaliyat;
			}
			set
			{
				if ((this._PishbiniEmkanPaziriyeAmaliyat != value))
				{
					this.OnPishbiniEmkanPaziriyeAmaliyatChanging(value);
					this.SendPropertyChanging();
					this._PishbiniEmkanPaziriyeAmaliyat = value;
					this.SendPropertyChanged("PishbiniEmkanPaziriyeAmaliyat");
					this.OnPishbiniEmkanPaziriyeAmaliyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeymateKol", DbType="NVarChar(1000)")]
		public string GeymateKol
		{
			get
			{
				return this._GeymateKol;
			}
			set
			{
				if ((this._GeymateKol != value))
				{
					this.OnGeymateKolChanging(value);
					this.SendPropertyChanging();
					this._GeymateKol = value;
					this.SendPropertyChanged("GeymateKol");
					this.OnGeymateKolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeymateVahed", DbType="NVarChar(1000)")]
		public string GeymateVahed
		{
			get
			{
				return this._GeymateVahed;
			}
			set
			{
				if ((this._GeymateVahed != value))
				{
					this.OnGeymateVahedChanging(value);
					this.SendPropertyChanging();
					this._GeymateVahed = value;
					this.SendPropertyChanged("GeymateVahed");
					this.OnGeymateVahedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeymateKolBarAsaseListeAdlBandi", DbType="NVarChar(1000)")]
		public string GeymateKolBarAsaseListeAdlBandi
		{
			get
			{
				return this._GeymateKolBarAsaseListeAdlBandi;
			}
			set
			{
				if ((this._GeymateKolBarAsaseListeAdlBandi != value))
				{
					this.OnGeymateKolBarAsaseListeAdlBandiChanging(value);
					this.SendPropertyChanging();
					this._GeymateKolBarAsaseListeAdlBandi = value;
					this.SendPropertyChanged("GeymateKolBarAsaseListeAdlBandi");
					this.OnGeymateKolBarAsaseListeAdlBandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaziyat", DbType="NVarChar(1000)")]
		public string Vaziyat
		{
			get
			{
				return this._Vaziyat;
			}
			set
			{
				if ((this._Vaziyat != value))
				{
					this.OnVaziyatChanging(value);
					this.SendPropertyChanging();
					this._Vaziyat = value;
					this.SendPropertyChanged("Vaziyat");
					this.OnVaziyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MogeiyateTahvilDadaneMahmooleBePeymankareHaml", DbType="NVarChar(1000)")]
		public string MogeiyateTahvilDadaneMahmooleBePeymankareHaml
		{
			get
			{
				return this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml;
			}
			set
			{
				if ((this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml != value))
				{
					this.OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanging(value);
					this.SendPropertyChanging();
					this._MogeiyateTahvilDadaneMahmooleBePeymankareHaml = value;
					this.SendPropertyChanged("MogeiyateTahvilDadaneMahmooleBePeymankareHaml");
					this.OnMogeiyateTahvilDadaneMahmooleBePeymankareHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasokhGooyiBarAsase", DbType="NVarChar(1000)")]
		public string PasokhGooyiBarAsase
		{
			get
			{
				return this._PasokhGooyiBarAsase;
			}
			set
			{
				if ((this._PasokhGooyiBarAsase != value))
				{
					this.OnPasokhGooyiBarAsaseChanging(value);
					this.SendPropertyChanging();
					this._PasokhGooyiBarAsase = value;
					this.SendPropertyChanged("PasokhGooyiBarAsase");
					this.OnPasokhGooyiBarAsaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasokhGooyiBarAsaseVasileyeHaml", DbType="NVarChar(1000)")]
		public string PasokhGooyiBarAsaseVasileyeHaml
		{
			get
			{
				return this._PasokhGooyiBarAsaseVasileyeHaml;
			}
			set
			{
				if ((this._PasokhGooyiBarAsaseVasileyeHaml != value))
				{
					this.OnPasokhGooyiBarAsaseVasileyeHamlChanging(value);
					this.SendPropertyChanging();
					this._PasokhGooyiBarAsaseVasileyeHaml = value;
					this.SendPropertyChanged("PasokhGooyiBarAsaseVasileyeHaml");
					this.OnPasokhGooyiBarAsaseVasileyeHamlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeymatBeEzayeHarTon", DbType="NVarChar(1000)")]
		public string GeymatBeEzayeHarTon
		{
			get
			{
				return this._GeymatBeEzayeHarTon;
			}
			set
			{
				if ((this._GeymatBeEzayeHarTon != value))
				{
					this.OnGeymatBeEzayeHarTonChanging(value);
					this.SendPropertyChanging();
					this._GeymatBeEzayeHarTon = value;
					this.SendPropertyChanged("GeymatBeEzayeHarTon");
					this.OnGeymatBeEzayeHarTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormePasokheGeymateHamleSangin", DbType="NVarChar(1000)")]
		public string FormePasokheGeymateHamleSangin
		{
			get
			{
				return this._FormePasokheGeymateHamleSangin;
			}
			set
			{
				if ((this._FormePasokheGeymateHamleSangin != value))
				{
					this.OnFormePasokheGeymateHamleSanginChanging(value);
					this.SendPropertyChanging();
					this._FormePasokheGeymateHamleSangin = value;
					this.SendPropertyChanged("FormePasokheGeymateHamleSangin");
					this.OnFormePasokheGeymateHamleSanginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaEhtesabeHazineyeOdateCantinereKhali", DbType="NVarChar(1000)")]
		public string BaEhtesabeHazineyeOdateCantinereKhali
		{
			get
			{
				return this._BaEhtesabeHazineyeOdateCantinereKhali;
			}
			set
			{
				if ((this._BaEhtesabeHazineyeOdateCantinereKhali != value))
				{
					this.OnBaEhtesabeHazineyeOdateCantinereKhaliChanging(value);
					this.SendPropertyChanging();
					this._BaEhtesabeHazineyeOdateCantinereKhali = value;
					this.SendPropertyChanged("BaEhtesabeHazineyeOdateCantinereKhali");
					this.OnBaEhtesabeHazineyeOdateCantinereKhaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateShamsi", DbType="NVarChar(1000)")]
		public string CreateDateShamsi
		{
			get
			{
				return this._CreateDateShamsi;
			}
			set
			{
				if ((this._CreateDateShamsi != value))
				{
					this.OnCreateDateShamsiChanging(value);
					this.SendPropertyChanging();
					this._CreateDateShamsi = value;
					this.SendPropertyChanged("CreateDateShamsi");
					this.OnCreateDateShamsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateMiladi", DbType="Date")]
		public System.Nullable<System.DateTime> CreateDateMiladi
		{
			get
			{
				return this._CreateDateMiladi;
			}
			set
			{
				if ((this._CreateDateMiladi != value))
				{
					this.OnCreateDateMiladiChanging(value);
					this.SendPropertyChanging();
					this._CreateDateMiladi = value;
					this.SendPropertyChanged("CreateDateMiladi");
					this.OnCreateDateMiladiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_ReplyToInquiry_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs", ThisKey="Id", OtherKey="ReplyToInquiryId")]
		public EntitySet<Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs
		{
			get
			{
				return this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs;
			}
			set
			{
				this._Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_ReplyToInquiry", Storage="_Asaei_EHaml_Inquiry", ThisKey="InquiryId", OtherKey="Id", IsForeignKey=true)]
		public Asaei_EHaml_Inquiry Asaei_EHaml_Inquiry
		{
			get
			{
				return this._Asaei_EHaml_Inquiry.Entity;
			}
			set
			{
				Asaei_EHaml_Inquiry previousValue = this._Asaei_EHaml_Inquiry.Entity;
				if (((previousValue != value) 
							|| (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asaei_EHaml_Inquiry.Entity = null;
						previousValue.Asaei_EHaml_ReplyToInquiries.Remove(this);
					}
					this._Asaei_EHaml_Inquiry.Entity = value;
					if ((value != null))
					{
						value.Asaei_EHaml_ReplyToInquiries.Add(this);
						this._InquiryId = value.Id;
					}
					else
					{
						this._InquiryId = default(Nullable<long>);
					}
					this.SendPropertyChanged("Asaei_EHaml_Inquiry");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_ReplyToInquiry = this;
		}
		
		private void detach_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs(Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz entity)
		{
			this.SendPropertyChanging();
			entity.Asaei_EHaml_ReplyToInquiry = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz")]
	public partial class Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _ReplyToInquiryId;
		
		private System.Nullable<long> _InquiryId;
		
		private string _InquiryType;
		
		private string _VasileName;
		
		private string _VahedePool;
		
		private System.Nullable<decimal> _GeymateVahed;
		
		private System.Nullable<int> _Tedad;
		
		private EntityRef<Asaei_EHaml_Inquiry> _Asaei_EHaml_Inquiry;
		
		private EntityRef<Asaei_EHaml_ReplyToInquiry> _Asaei_EHaml_ReplyToInquiry;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnReplyToInquiryIdChanging(System.Nullable<long> value);
    partial void OnReplyToInquiryIdChanged();
    partial void OnInquiryIdChanging(System.Nullable<long> value);
    partial void OnInquiryIdChanged();
    partial void OnInquiryTypeChanging(string value);
    partial void OnInquiryTypeChanged();
    partial void OnVasileNameChanging(string value);
    partial void OnVasileNameChanged();
    partial void OnVahedePoolChanging(string value);
    partial void OnVahedePoolChanged();
    partial void OnGeymateVahedChanging(System.Nullable<decimal> value);
    partial void OnGeymateVahedChanged();
    partial void OnTedadChanging(System.Nullable<int> value);
    partial void OnTedadChanged();
    #endregion
		
		public Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz()
		{
			this._Asaei_EHaml_Inquiry = default(EntityRef<Asaei_EHaml_Inquiry>);
			this._Asaei_EHaml_ReplyToInquiry = default(EntityRef<Asaei_EHaml_ReplyToInquiry>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyToInquiryId", DbType="BigInt")]
		public System.Nullable<long> ReplyToInquiryId
		{
			get
			{
				return this._ReplyToInquiryId;
			}
			set
			{
				if ((this._ReplyToInquiryId != value))
				{
					if (this._Asaei_EHaml_ReplyToInquiry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReplyToInquiryIdChanging(value);
					this.SendPropertyChanging();
					this._ReplyToInquiryId = value;
					this.SendPropertyChanged("ReplyToInquiryId");
					this.OnReplyToInquiryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryId", DbType="BigInt")]
		public System.Nullable<long> InquiryId
		{
			get
			{
				return this._InquiryId;
			}
			set
			{
				if ((this._InquiryId != value))
				{
					if (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInquiryIdChanging(value);
					this.SendPropertyChanging();
					this._InquiryId = value;
					this.SendPropertyChanged("InquiryId");
					this.OnInquiryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InquiryType", DbType="NVarChar(1000)")]
		public string InquiryType
		{
			get
			{
				return this._InquiryType;
			}
			set
			{
				if ((this._InquiryType != value))
				{
					this.OnInquiryTypeChanging(value);
					this.SendPropertyChanging();
					this._InquiryType = value;
					this.SendPropertyChanged("InquiryType");
					this.OnInquiryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VasileName", DbType="NVarChar(1000)")]
		public string VasileName
		{
			get
			{
				return this._VasileName;
			}
			set
			{
				if ((this._VasileName != value))
				{
					this.OnVasileNameChanging(value);
					this.SendPropertyChanging();
					this._VasileName = value;
					this.SendPropertyChanged("VasileName");
					this.OnVasileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VahedePool", DbType="NVarChar(1000)")]
		public string VahedePool
		{
			get
			{
				return this._VahedePool;
			}
			set
			{
				if ((this._VahedePool != value))
				{
					this.OnVahedePoolChanging(value);
					this.SendPropertyChanging();
					this._VahedePool = value;
					this.SendPropertyChanged("VahedePool");
					this.OnVahedePoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeymateVahed", DbType="Money")]
		public System.Nullable<decimal> GeymateVahed
		{
			get
			{
				return this._GeymateVahed;
			}
			set
			{
				if ((this._GeymateVahed != value))
				{
					this.OnGeymateVahedChanging(value);
					this.SendPropertyChanging();
					this._GeymateVahed = value;
					this.SendPropertyChanged("GeymateVahed");
					this.OnGeymateVahedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad", DbType="Int")]
		public System.Nullable<int> Tedad
		{
			get
			{
				return this._Tedad;
			}
			set
			{
				if ((this._Tedad != value))
				{
					this.OnTedadChanging(value);
					this.SendPropertyChanging();
					this._Tedad = value;
					this.SendPropertyChanged("Tedad");
					this.OnTedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_Inquiry_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_Inquiry", ThisKey="InquiryId", OtherKey="Id", IsForeignKey=true)]
		public Asaei_EHaml_Inquiry Asaei_EHaml_Inquiry
		{
			get
			{
				return this._Asaei_EHaml_Inquiry.Entity;
			}
			set
			{
				Asaei_EHaml_Inquiry previousValue = this._Asaei_EHaml_Inquiry.Entity;
				if (((previousValue != value) 
							|| (this._Asaei_EHaml_Inquiry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asaei_EHaml_Inquiry.Entity = null;
						previousValue.Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Remove(this);
					}
					this._Asaei_EHaml_Inquiry.Entity = value;
					if ((value != null))
					{
						value.Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Add(this);
						this._InquiryId = value.Id;
					}
					else
					{
						this._InquiryId = default(Nullable<long>);
					}
					this.SendPropertyChanged("Asaei_EHaml_Inquiry");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asaei_EHaml_ReplyToInquiry_Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyaz", Storage="_Asaei_EHaml_ReplyToInquiry", ThisKey="ReplyToInquiryId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Asaei_EHaml_ReplyToInquiry Asaei_EHaml_ReplyToInquiry
		{
			get
			{
				return this._Asaei_EHaml_ReplyToInquiry.Entity;
			}
			set
			{
				Asaei_EHaml_ReplyToInquiry previousValue = this._Asaei_EHaml_ReplyToInquiry.Entity;
				if (((previousValue != value) 
							|| (this._Asaei_EHaml_ReplyToInquiry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asaei_EHaml_ReplyToInquiry.Entity = null;
						previousValue.Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Remove(this);
					}
					this._Asaei_EHaml_ReplyToInquiry.Entity = value;
					if ((value != null))
					{
						value.Asaei_EHaml_ReplyToNoVaTedadeVasileyeMoredeNiyazs.Add(this);
						this._ReplyToInquiryId = value.Id;
					}
					else
					{
						this._ReplyToInquiryId = default(Nullable<long>);
					}
					this.SendPropertyChanged("Asaei_EHaml_ReplyToInquiry");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
