//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asaei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asaei_EHaml_Inquiry
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string HadafeShomaAzEstelam { get; set; }
        public string NoeVasileyeMoredeNiyaz { get; set; }
        public string NoeHaml { get; set; }
        public string NoeMahmoole { get; set; }
        public string NoeMahmoole2 { get; set; }
        public string YekAksAzMahmoole { get; set; }
        public string CodeHsMahmoole { get; set; }
        public string VazneMahmooleKiloGeram { get; set; }
        public string ListeKalahayeKhatarnak { get; set; }
        public string NoeBasteBandi { get; set; }
        public string BaEhtesabeBimeyeMasooliyat { get; set; }
        public string FormeVooroodeArzeshBarAsaseVasileyeHaml { get; set; }
        public string FormeVorodeArzeshBarAsaseListeAdlBandi { get; set; }
        public string FormePakingList { get; set; }
        public string BaEhtesabeHazineyeBarGiriDarMabda { get; set; }
        public string EstelamBarAsase { get; set; }
        public string OstaneMabda { get; set; }
        public string MantageyeMabda { get; set; }
        public string ShahreMabda { get; set; }
        public string MogeiyateTahvilDadaneMahmooleBePeymankareHaml { get; set; }
        public string OstaneMagsad { get; set; }
        public string MantageyeMagsad { get; set; }
        public string ShahreMagsad { get; set; }
        public string BaEhtesabeHazineyeTakhliyeDarMagsad { get; set; }
        public string TarikheAgazeAmaliyatShamsi { get; set; }
        public string TarikheEtebareEstelamShamsi { get; set; }
        public Nullable<System.DateTime> TarikheAgazeAmaliyatMiladi { get; set; }
        public Nullable<System.DateTime> TarikheEtebareEstelamMiladi { get; set; }
        public string InquiryType { get; set; }
        public string CreateDateShamsi { get; set; }
        public Nullable<System.DateTime> CreateDateMiladi { get; set; }
        public string Tedad { get; set; }
        public string HadeAxareVazneMahmoole { get; set; }
        public string NoeVasileyeMoredeNiyaz2 { get; set; }
        public string VazneHarVahedeMahmooleKiloGeram { get; set; }
        public string BaEhtesabeHazineyeOdateKantinereKhali { get; set; }
    }
}
