//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHaml
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asaei_EHaml_ReplyToInquiry
    {
        public long Id { get; set; }
        public Nullable<long> InquiryId { get; set; }
        public string InquiryType { get; set; }
        public Nullable<long> ServentUserId { get; set; }
        public string KoleModatZamaneHaml { get; set; }
        public string ZamaneAmadegiBarayShoorooeAmaliyatShamsi { get; set; }
        public Nullable<System.DateTime> ZamaneAmadegiBarayShoorooAmaliyatMiladi { get; set; }
        public string GozaresheAmaliyateRoozane { get; set; }
        public string PishbiniEmkanPaziriyeAmaliyat { get; set; }
        public string GeymateKol { get; set; }
        public string GeymateVahed { get; set; }
        public string GeymateKolBarAsaseListeAdlBandi { get; set; }
        public string Vaziyat { get; set; }
        public string MogeiyateTahvilDadaneMahmooleBePeymankareHaml { get; set; }
        public string PasokhGooyiBarAsase { get; set; }
        public string PasokhGooyiBarAsaseVasileyeHaml { get; set; }
        public string GeymatBeEzayeHarTon { get; set; }
        public string FormePasokheGeymateHamleSangin { get; set; }
        public string BaEhtesabeHazineyeOdateCantinereKhali { get; set; }
        public string CreateDateShamsi { get; set; }
        public Nullable<System.DateTime> CreateDateMiladi { get; set; }
    }
}
