//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asaei_EHaml
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asaei_EHaml_NoeVasileyeHaml
    {
        public int Id { get; set; }
        public string NameVasile { get; set; }
        public int ShomareyeTartib { get; set; }
    }
}
