//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asaei_EHaml
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHamlDBEntities : DbContext
    {
        public EHamlDBEntities()
            : base("name=EHamlDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asaei_EHaml_Inquiry> Asaei_EHaml_Inquiry { get; set; }
        public virtual DbSet<Asaei_EHaml_ListeKalahayeKhatarnak> Asaei_EHaml_ListeKalahayeKhatarnak { get; set; }
        public virtual DbSet<Asaei_EHaml_NoeVasileyeHaml> Asaei_EHaml_NoeVasileyeHaml { get; set; }
        public virtual DbSet<Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz> Asaei_EHaml_NoVaTedadeVasileyeMoredeNiyaz { get; set; }
    }
}
